version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: gunicorn --bind 0.0.0.0:8000 broadcast_server.wsgi:application
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DEBUG=1

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: npm start

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: broadcast_db
      POSTGRES_USER: broadcast_user
      POSTGRES_PASSWORD: your_password_here
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"