version: '3.8'

services:
  backend:
    build: ./backend
    command: gunicorn --bind 0.0.0.0:8000 broadcast_server.wsgi:application
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./backend/static:/app/static
      - ./backend/media:/app/media
    depends_on:
      - backend
      - frontend

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  redis:
    image: redis:latest

volumes:
  postgres_data: